name: Steps Examples
on: 
    workflow_dispatch:

jobs: 
    steps-examples:
        runs-on: ubuntu-latest
        steps:
            - name: make directory
              run: mkdir testmachine
            
            - name: execute uname command
              run: uname -a > testmachine/output.txt

            - name: check directory output
              run: ls -alhR testmachine

            - name:  check contents output.txt
              run: cat testmachine/output.txt
        
		
    
