name: Uses Examples
on:
  workflow_dispatch

jobs:
  uses-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: setup python on runner
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: run the script from the repo
      - run: python my_script.py
